### ISSUE TITLE
How to download the asf-jupyter-data through aws?

### ISSUE THREAD

**Issue by pizzawoo** [parosen/Geo-SInC#93]
Hello everyone, I'm currently learning ISCE2 with the notebooks in /EarthScope2023. It seems that I have no access for the data which shall be downloaded from an AWS bucket.
For instance, in [0.4_Geographic_Information_Science_using_GDAL/01_IntroToRasterData.ipynb](https://github.com/parosen/Geo-SInC/blob/main/EarthScope2023/0.4_Geographic_Information_Science_using_GDAL/01_IntroToRasterData.ipynb),after running
`!aws --region=us-east-1 --no-sign-request s3 cp s3://asf-jupyter-data/unavco2021/stripmap.zip $path`
I got   
_fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden_

Should I use the OpenSAR-Docker or directly, any other access to the data in the courses?
Thanks.

**Comment by EJFielding** [comment]
Hello, I think that the `region=us-east-1` AWS bucket from the UNAVCO2021 course may only work from the ASF OpenSARLab machines. Look at the AWS bucket specified in the `1.4_stripmap` notebook to see the new `asf-jupyter-data-west` AWS bucket that should be open to all.

**Comment by pizzawoo** [comment]
Thanks for the quick reply. I replaced the s3 address `//asf-jupyter-data/` with `//asf-jupyter-data-west/` and aws download completed successfully. 
Again,thank you very much! Issue solved.
